### ISSUE TITLE
support customize repo and branch

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#13]
The current version is using [AdoptOpenJDK/openjdk-tests](https://github.com/AdoptOpenJDK/openjdk-tests.git) as default repo to run AQA tests. For AdoptOpenJDK/openjdk-tests contributors it's better to support personal repo and feature branch for a PR build.

Run-aqa `git clone` `AdoptOpenJDK/openjdk-tests` and `AdoptOpenjdk/TKG`. Enable this `run-aqa` can be also run against those two repos' personal branch by push or create PRs.

**Comment by sophia-guo** [comment]
A boolean value on whether the personalRepo should be used could be added.

If false, using default `AdoptOpenJDK/openjdk-tests`. Otherwise using PR's github environment variable to get user's repo and branch. ( no need for users to input those information)

**Comment by sophia-guo** [comment]
There are cases that user would like to set both [openjdk-test](https://github.com/AdoptOpenJDK/openjdk-test) and [TKG](https://github.com/AdoptOpenJDK/TKG) .  Then https://github.com/AdoptOpenJDK/run-aqa/issues/13#issuecomment-619042722 won't work for this. Should we also support the user case by setting both [openjdk-test](https://github.com/AdoptOpenJDK/openjdk-test) and [TKG](https://github.com/AdoptOpenJDK/TKG)? Thoughts?

**Comment by smlambert** [comment]
Yes, if we have learned anything from Grinders, people want both the flexibility to change absolutely every piece of what could be used by testing to point to their own branch (which includes openjdk-tests, jdk-jdk{Version}u, TKG, STF, openjdk-systemtest, openj9-systemtest, openj9, etc), but they also want it to be simple.  ( insert fatigued laugh by @smlambert here ;) ).

I have been thinking about this from Grinder point of view and the dilemna of parameter creep... people wanting to keep adding new parameters to make testing even more flexible.  In Grinders, I would like to change from the 2 parameters per repo approach to a single string which is copy-paste-able from github PRs (the id:branch string associated with the PR, which can then be parsed by Jenkinsfilebase or Run-AQA).  

This helps reduce the number of inputs, but there will still be demand for the following, I believe:

| Repo name | input param default | When required | 
| --- | --- | --- |
| openjdk-tests | AdoptOpenJDK:master | always |
| TKG | AdoptOpenJDK:master | always |
| jdk-jdk{Version}u | AdoptOpenJDK:master | BUILD_LIST=openjdk |
| STF | AdoptOpenJDK:master |  BUILD_LIST=system |
| openjdk-systemtest | AdoptOpenJDK:master | BUILD_LIST=system |
| openj9 | AdoptOpenJDK:master | BUILD_LIST=functional |
| openj9-systemtest | AdoptOpenJDK:master | BUILD_LIST=system, JDK_IMPL=openj9 |

**Comment by sophia-guo** [comment]
Current [openjdk-tests](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml) don't support personal repo (either for hotspot or for openj9) . I will open an issue in openjdk-tests.

**Comment by smlambert** [comment]
Thanks @sophia-guo, I was aware that the current openjdk-tests do not support personal repo at the moment for jdk-jdk{Version}u items, but I actually think we should move it out to be a full-fledged parameter for several reasons:
-  especially now with openjdk project Skara means many openjdk developers may have their own GitHub fork/branches)

- simplifies the current openjdk/build.xml logic, as there are several 'exception' cases now (like for aarch64, etc), where it would just be easier if we passed in the repo/branch names explicitly

- it means we treat all repos that contain test materials in a consistent/predictable manner (a pattern of being able to set each to my own fork/branch)

**Comment by sophia-guo** [comment]
Yes, current all those repos information was scattered many different place and most of time they are exported environment variable to make them visible. I was thinking it's not a good way. Agree that we should do some change!

**Comment by sophia-guo** [comment]
Close in favour of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1873
