### ISSUE TITLE
New functional test defaultLazySymbolResolution fails to compile for JDK_IMPL=hotspot

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/run-aqa#37]
https://github.com/AdoptOpenJDK/run-aqa/runs/1354982487?check_suite_focus=true#step:4:1651

BUILD FAILED
/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
/home/runner/work/run-aqa/run-aqa/openjdk-tests/functional/build.xml:52: The following error occurred while executing this line:
/home/runner/work/run-aqa/run-aqa/openjdk-tests/functional/cmdLineTests/build.xml:40: The following error occurred while executing this line:
/home/runner/work/run-aqa/run-aqa/openjdk-tests/functional/cmdLineTests/defaultLazySymbolResolution/build.xml:54: The following error occurred while executing this line:
/home/runner/work/run-aqa/run-aqa/openjdk-tests/functional/cmdLineTests/defaultLazySymbolResolution/build.xml:40: Directory does not exist: /home/runner/work/run-aqa/run-aqa/jvmtest/functional/cmdLineTests/defaultLazySymbolResolution

**Comment by smlambert** [comment]
FYI @llxia

**Comment by llxia** [comment]
`cmdLineTester_defaultLazySymbolResolution` uses `VM_Test ` and `VM_Test ` only compiles when JDK_IMPL= openj9 or ibm. We should update [defaultLazySymbolResolution/build.xml](https://github.com/eclipse/openj9/blob/40f5a96154580755c3bc252241c17a77c5d6d35a/test/functional/cmdLineTests/defaultLazySymbolResolution/build.xml) to skip in hotspot case. Simliar to https://github.com/eclipse/openj9/blob/40f5a96154580755c3bc252241c17a77c5d6d35a/test/functional/VM_Test/build.xml#L206-L214

And we should also update [forceLazySymbolResolution/build.xml](https://github.com/eclipse/openj9/blob/40f5a96154580755c3bc252241c17a77c5d6d35a/test/functional/cmdLineTests/forceLazySymbolResolution/build.xml).

@OscarQQ could you help to fix this? Thanks

**Comment by llxia** [comment]
PR https://github.com/eclipse/openj9/pull/11115 is merged. Close this issue. If the problem still exists, please reopen.
