### ISSUE TITLE
DaaLoadTest_daa2 and DaaLoadTest_daa2_ConcurrentScavenge fails (jdk8/j9)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/run-aqa#38]
https://github.com/AdoptOpenJDK/run-aqa/runs/1354982540?check_suite_focus=true#step:4:16847

https://github.com/AdoptOpenJDK/run-aqa/runs/1354982540?check_suite_focus=true#step:4:17670

DLT class net.openj9.test.binaryData.TestLong2ByteArrayNumBytes Total: 51 Fail: 1 Ignore: 0
DLT 	FAILURE: testValidIndexForFourNumBytes(net.openj9.test.binaryData.TestLong2ByteArrayNumBytes) - arrays first differed at element [254]; expected:<-119> but was:<-1>

**Comment by sophia-guo** [comment]
Closed. The fix was in https://github.com/AdoptOpenJDK/openjdk-systemtest.
