### ISSUE TITLE
cmdLineTester_SCCommandLineOptionTests_1 fail (jdk8,11,15/j9)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/run-aqa#39]
https://github.com/AdoptOpenJDK/run-aqa/runs/1354982566?check_suite_focus=true#step:4:50735
Testing: Run !printallcallsites
Test start time: 2020/11/04 21:36:14 Coordinated Universal Time
Running command: /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/jdmpview -core j9core.dmp
Time spent starting: 2 milliseconds
Time spent executing: 689 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Could not load dump file and/or could not load XML file: null
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 

https://github.com/AdoptOpenJDK/run-aqa/runs/1354982566?check_suite_focus=true#step:4:53130
 [OUT] nameOption2: Expected to find the cache name
 [OUT] TEST PASSED
 [ERR] JVMSHRC806I Compressed references persistent shared cache "runner" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.

**Comment by sophia-guo** [comment]
Looks like cmdLineTester_callsitedbgddrext_openj9 passed in recent running. https://github.com/AdoptOpenJDK/run-aqa/runs/1476255594?check_suite_focus=true#step:4:33468. Not sure if it's intermittent or fixed.

**Comment by smlambert** [comment]
Updating this issue to remove cmdLineTester_callsitedbgddrext_openj9 from the heading.  That test was failing consistently a few weeks ago, but has not failed for a while.  I do not see an obvious PR/fix that would change behaviour, but we can raise it as a separate issue if its turned into something intermittent.

**Comment by sophia-guo** [comment]
Update cmdLineTester_SCCommandLineOptionTests_1 failures on linux with jdk8/11/15 ( Original one is the failure of cmdLineTester_callsitedbgddrext_openj9):

Testing: nameOption2
Test start time: 2020/12/02 20:42:49 Coordinated Universal Time
Running command: sh nameOption2.sh /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin
Time spent starting: 1 milliseconds
Time spent executing: 272 milliseconds
Test result: FAILED
 [OUT] Hello, world!
 [OUT] TEST PASSED
 [OUT] nameOption2: TEST FAILED
 [OUT] nameOption2: Expected to find the cache name
 [OUT] TEST PASSED
 [ERR] JVMSHRC806I Compressed references persistent shared cache "runner" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
>> Success condition was found: [Output match: TEST PASSED]
>> Failure condition was found: [Output match: TEST FAILED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

...
Testing: nameOption4
Test start time: 2020/12/02 20:42:50 Coordinated Universal Time
Running command: sh nameOption4.sh /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin
Time spent starting: 8 milliseconds
Time spent executing: 276 milliseconds
Test result: FAILED
 [OUT] Hello, world!
 [OUT] TEST PASSED
 [OUT] nameOption4: TEST FAILED
 [OUT] nameOption4: Expected to find the cache name
 [OUT] TEST PASSED
 [ERR] JVMSHRC806I Compressed references persistent shared cache "_runner_docker" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
>> Success condition was found: [Output match: TEST PASSED]
>> Failure condition was found: [Output match: TEST FAILED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

**Comment by sophia-guo** [comment]
cmdLineTester_callsitedbgddrext_openj9 reopened in #50

**Comment by sophia-guo** [comment]
Test nameOption2 and nameOption4 get the username from the environment variable LOGNAME
`export TESTUSER=$LOGNAME`

to match the shared Cache generated by NAME=_%u.

In github runner ubuntu environment _%u is runner and $LOGNAME turns out be empty ( github runner macos $LOGNAME  is runner, so test passes with macos). 

This actually should also affect test nameOption, which set DEFAULT_CACHE_NAME="sharedcc_$TESTUSER" . However as TESTUSER is empty so `grep "$DEFAULT_CACHE_NAME" $TESTSCRIPT.out` will return 0. Kind of luck, test is actually fragile. 

Next step would need to figure out why $LOGNAME is empty on ubuntu runner, and be `runner` on macos runner. Is this expected?

**Comment by sophia-guo** [comment]
LOGNAME is not in the Ubuntu GitHub Actions Environment Variables List. Instead RUNNER_USER is the environment for the user runner. There’s always a chance that the list will get outdated as soon as a new container is configured. We will put a warning if it happens and update our fixes.
