### ISSUE TITLE
cmdLineTester_CryptoTest fails fails ( jdk8 with openj9  on mac)

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#57]
https://github.com/AdoptOpenJDK/run-aqa/runs/1539658923?check_suite_focus=true

```
*** Starting test suite: OpenSSL Tests ***
Testing: CryptoTest
Test start time: 2020/12/12 00:12:42 Coordinated Universal Time
Running command: "/Users/runner/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/java"   -Djdk.nativeCryptoTrace=true -cp "/Users/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/openssl/"openssltest.jar org.openj9.test.openssl.CryptoTest
Time spent starting: 40 milliseconds
Time spent executing: 355 milliseconds
Test result: FAILED
Output from test:
 [OUT] Crypto test COMPLETED
 [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
 [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
>> Success condition was not found: [Output match: using native crypto library]
>> Required condition was found: [Output match: Crypto test COMPLETED]
>> Failure condition was found: [Output match: Native crypto library load failed]
>> Failure condition was not found: [Output match: Crypto test FAILED]


---TEST RESULTS---
Number of PASSED tests: 0 out of 1
Number of FAILED tests: 1 out of 1

---SUMMARY OF FAILED TESTS---
CryptoTest
-----------------------------


cmdLineTester_CryptoTest_0_FAILED
```

Same failures on AdoptOpenJDK jenkins:
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_sanity.functional_x86-64_mac/54/console

**Comment by sophia-guo** [comment]
This only happens to jdk8 on mac in AdoptOpenjdk and run-aqa. @pshipton any idea about this?

**Comment by sophia-guo** [comment]
Would like to run a grinder in openj9 jenkins( which could grab nightly sdk from AdoptOpenjdk) to see if it fails. If passes probably a machine configure issue if fails there would be build difference between adoptopenjdk and openj9? ( as it passes in openj9 nighlty jenkins).

**Comment by pshipton** [comment]
For the crypto test to pass you need to enable and bundle openssl. Are you use the following options?

get_source.sh option `--openssl-version=1.1.1i`
configure optinos: `--with-openssl=fetched --enable-openssl-bundling`

**Comment by pshipton** [comment]
Fails on Adopt build as well https://ci.eclipse.org/openj9/view/Test/job/Grinder/1284

**Comment by sophia-guo** [comment]
We are using the nightly jdk from AdoptOpenjdk. From the build job I can see that for jdk11 and up the build use configuration `--with-openssl=fetched --enable-openssl-bundling` 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/851/consoleFull

While for  jdk8 looks like it's built without that configure options:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/807/consoleFull

Not sure it's expected or not.

**Comment by pshipton** [comment]
It's wrong. I've opened an issue https://github.com/AdoptOpenJDK/openjdk-build/issues/2309

**Comment by sophia-guo** [comment]
Tests passed in https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_sanity.functional_x86-64_mac/60/, which was triggered by upstream nightly build.

run-aqa run against the nightly build SDK by AdoptOpenJDK API 3, which stays as 20201208_800 and failed: https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9

 Eclipse OpenJ9 VM (build openj9-0.24.0-m1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201208_800 (JIT enabled, AOT enabled)
10:39:20  OpenJ9   - c757b5115
10:39:20  OMR      - 5080dab1e
10:39:20  JCL      - 9910cb2350 based on jdk8u282-b04)

Will close this and probably worth to know why jdk8 hasn't been published nightly as expected? Upstream nightly build looks good https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/ .

**Comment by smlambert** [comment]
An issue should get raised at https://github.com/AdoptOpenJDK/openjdk-api-v3/issues to report the problem that its not been serving up nightly builds, (serving some build that is from 2 weeks ago?).

**Comment by sophia-guo** [comment]
Issue opened at api-v3 https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/337
