### ISSUE TITLE
 All functional tests builds with openj9 fail

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#62]
The error:
https://github.com/AdoptOpenJDK/run-aqa/runs/1566377410?check_suite_focus=true

```
 [javac] error: error reading /home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/org.eclipse.osgi_3.16.100.v20200904-1304.jar; error in opening zip file
    [javac] 1 error
```

**Comment by sophia-guo** [comment]
```
     [exec] downloading  https://mirror.umd.edu/eclipse/equinox/drops/S-4.18M1a-202010120320/org.eclipse.osgi_3.16.100.v20200904-1304.jar
     [exec] --> file downloaded to /home/runner/work/runaqaTest/runaqaTest/openjdk-tests/TKG/../TKG/lib/org.eclipse.osgi_3.16.100.v20200904-1304.jar
     [exec] Expected sha is: e0c1c2fa5e5f520d2347f9e7a7d2873e3b96bab3,
     [exec] Actual sha is  : 55df4256e88dbe8795fea9f6ac50b2f8e0215eb1.
     [exec] ERROR: sha checksum error.
```

@llxia @LongyuZhang idea?

**Comment by llxia** [comment]
It looks like the mirror site cannot be found:  https://mirror.umd.edu/eclipse/equinox/drops/S-4.18M1a-202010120320/org.eclipse.osgi_3.16.100.v20200904-1304.jar

**Comment by llxia** [comment]
@sophia-guo It may be better to use [Jenkins job](https://ci.adoptopenjdk.net/job/test.getDependency/lastSuccessfulBuild/artifact/) to pre-download artifacts. Otherwise, run-aqa will depend on each 3rd party jar downloading.

**Comment by sophia-guo** [comment]
Fixed by https://github.com/AdoptOpenJDK/TKG/pull/134. Close it.
