### ISSUE TITLE
Both openjdk tests with ubuntu and mac failed when retrieving jdk source

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#71]
Both openjdk tests with ubuntu and mac failed when retrieving jdk source: https://github.com/AdoptOpenJDK/run-aqa/runs/2025584017?check_suite_focus=true

```
getOpenjdk:
     [echo] Using a git ls-remote command to determine if the jdk source repo has an available 'u' version yet.
     [echo] git ls-remote -h https://github.com/AdoptOpenJDK/openjdk-jdk16u.git
     [exec] fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

The failure is caused by the change https://github.com/AdoptOpenJDK/openjdk-tests/pull/2287

**Comment by sophia-guo** [comment]
@adamfarley Could you please take a look?

**Comment by sophia-guo** [comment]
Before the change job works fine on linux and macos, hangs on windows when retrieving openjdk source:
https://github.com/AdoptOpenJDK/run-aqa/runs/2007503879?check_suite_focus=true
```
getOpenjdk:
     [exec] error: could not lock config file /home/runneradmin/.gitconfig: No such file or directory
     [exec] Result: 255
     [echo] git ls-remote -h https://github.com/AdoptOpenJDK/openjdk-jdk16u.git
Error: The operation was canceled.
```

With the change job on windows works, failed on both linux and macos.

**Comment by adamfarley** [comment]
Aw. :(

Will fix. Looking now.

**Comment by adamfarley** [comment]
Ok, this should fix it: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2338

Proven to work: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7489/console

**Comment by adamfarley** [comment]
I thought the trycatch was needed originally, as there was a reason for the failonerror to be set to true in the inner exec, but in hindsight I think that was just left over from something else.

**Comment by adamfarley** [comment]
@sophia-guo - Since the change is merged, can you confirm the problem is gone and close this issue please?

**Comment by sophia-guo** [comment]
Last run sha is b12a4926191e867b4ed8f5c9a598700fce8c66f7, which hasn't have @adamfarley your changes and failed with same issue. https://github.com/AdoptOpenJDK/run-aqa/runs/2042869858?check_suite_focus=true.

Will wait for today's run and see if it works or not.

**Comment by sophia-guo** [comment]
@adamfarley thanks! I can confirm that the error is fixed.
